### ISSUE TITLE
what about "infinity"?

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#11]
A question: what about "infinity"?

I see, in the specifications of XCSP3, that is possible to define variable as

    <var id=" x "> 0..+infinity </var>
    <var id=" y "> -infinity..+infinity </var>

but I don't understand if this is part of XCSP3-core or not.

Your parser will support "infinity"?

**Comment by xcsp3team** [comment]
No, it does not support infinity.
I need to fix the bug: the same that appear in issue #10

**Comment by massimomorara** [comment]
I know that **now** your parser doesn't support "infinity".
Doensn't support it because isn't XCSP3-core or because others reasons? 
And are you going to support it, in the future?

**Comment by xcsp3team** [comment]
I need to talk of this with my colleagues. They are in holidays. More news in few weeks.

**Comment by massimomorara** [comment]
Yes: it's the wrong season to pose this sort of question. :-)
No problem: I wait.

**Comment by xcsp3team** [comment]
Nothing prevents the use of infinity in XCSP3-core (because it is simply stated that only integer variables are considered in XCSP3-core, without any additional precision).
However, in the context of the competition, is is clearly indicated that infinity is not authorized.

A new version of the specifications (with mainly a few extensions) is planned  in October. More details about XCSP3-core will be given.

Concerning the use of infinity, it will be handled by parsers (just by using a special reserved value). I will discuss with Gilles about that topic.

 Christophe
